### PR TITLE
Create 404 page

### PR DESCRIPTION
**Pull request by lunson**
Creates and styles a 404 page. 

Please note that link to the old site will need to be corrected before deployment and that the copy may need some editing.

### CODE REVIEW

**Comment by sbesson** [comment]
See e.g. http://snoopycrimecop.github.io/www.openmicroscopy.org/doesnotexist

**Comment by pwalczysko** [comment]
Tried the link offered by @sbesson . Great stuff, clear message, and the "recovery" button worked as well. Thank you @lunson

**Comment by pwalczysko** [comment]
It seems there is one more ToDo during deployment for this PR, see screenshot below. 

screen shot 2017-07-11 at 10 12 01

@kennethgillen

**Comment by sbesson** [comment]
@pwalczysko @lunson we just spinned up the new URL for the legacy website at https://www-legacy.openmicroscopy.org/ with @kennethgillen so this can be used in the current placeholder either here or in a follow-up PR.

**Comment by lunson** [comment]
Added the legacy link. Thanks, @pwalczysko @sbesson @kennethgillen! Should be good to go.

**Pull request merged**
