### PR TITLE
Experimental: Attempt to include sha256 in release notes

### PR DESCRIPTION
**Pull request by manics**
This could be directly copied into the ansible playbook.

Untested. Based on
- https://github.com/travis-ci/dpl/issues/155#issuecomment-313177958
- https://github.com/travis-ci/travis-ci/issues/6423#issuecomment-400980292

### CODE REVIEW

**Comment by sbesson** [comment]
Coming briefly back to this proposal, an alternative that is used by many open-source projects to workaround the absence of checksums in the [Releases assets](https://developer.github.com/v3/repos/releases/) is to create a second asset containing the checksum e.g.`${TRAVIS_REPO_SLUG#*/}.tar.gz.sha{1,256,512}`.

**Comment by sbesson** [comment]
Following the deployment of today's website, I came back to this proposal. I have tested the various implementation on my fork:

- https://github.com/sbesson/www.openmicroscopy.org/releases/tag/2019.02.18-2 is the direct outcome of aeb5cac
- https://github.com/sbesson/www.openmicroscopy.org/releases/tag/2019.02.18-3 is the output of https://github.com/openmicroscopy/www.openmicroscopy.org/pull/255#issuecomment-427867011
- https://github.com/sbesson/www.openmicroscopy.org/releases/tag/2019.02.18-4 is a variant to aeb5cac using `sha256sum --tag` to try and improve the readability of the release notes

Propose to get one of these options (or a better suggestion) in so that we can test the cut-n-paste workflow in the upcoming deployments. Any preference @manics @joshmoore @jburel ?

**Comment by mtbc** [comment]
My favorite is 2019.02.18-4 - at the least, good to mention which checksum algorithm is being applied!

**Comment by joshmoore** [comment]
Works for me as well. If we move this strategy to other repos, I could see extending this to include something along the lines of:

```
export BODY=$(cat CHANGELOG.md)
```

(from dpl-155)

**Comment by manics** [comment]
Not `2019.02.18-3` because it forces you to download the checksum before you can open it

**Comment by sbesson** [comment]
Agreed, my hope is that this would open in a browser but effectively it gets you to download the entire `SHASUMS` file. Objection to `2019.02.18-4` (as per the last commits added to this PR)?

Also all in favor of improving the content of the body as suggested in https://github.com/openmicroscopy/www.openmicroscopy.org/pull/255#issuecomment-465045559 wherever we make the effort of maintaining a changelog/news file.

**Comment by manics** [comment]
One more factor to bear in mind: We'll eventually automate the full deployment workflow, so tagging this repo automatically updates the deployment playbook, runs tests, and deploys to production with minimal interaction. Can we do anything to make that easier?

**Comment by sbesson** [comment]
Very preliminary thought would be to start setting up GitHub webhooks and consuming [release events](https://developer.github.com/v3/activity/events/types/#releaseevent). As per this PR additions, the content of `assets` and `body` should contain all the necessary information to update the deployment playbook.

The complete workflow obviously need some more thorough scoping. Immediately, I do not see any reason not to start integrating this as an incremental step.

**Comment by manics** [comment]
Maybe combine solutions 3 + 4? then downstream scripts can consume the sha artifact without parsing the text of the release.

**Comment by sbesson** [comment]
See https://github.com/sbesson/www.openmicroscopy.org/releases/tag/2019.02.19 for the output of the last commit

**Pull request merged**
