### PR TITLE
Add social hub/landing page

### PR DESCRIPTION
**Pull request by lunson**
(Not ready for merge; I need real content!)

Per https://trello.com/c/dl2kR5so/29-weekly-meeting-notes-to-live-on-website-or-not this creates a landing page for meeting notes and reference links for the community. I need real content in order to balance the design.

### CODE REVIEW

**Comment by joshmoore** [comment]
Perhaps "On the Web"?

**Comment by hflynn** [comment]
Staged at https://snoopycrimecop.github.io/www.openmicroscopy.org/on-the-web/

Mostly it looks like we mainly need a blurb before this is ready to go in its first iteration. Possibly we should decide what else we want to stick here before we make any of it live though.

**Comment by lunson** [comment]
Per meeting with @sbesson @jburel @hflynn this morning, we'll add GitHub for now to go live, and will add on others as necessary. @hflynn All yours now to add a blurb. Thanks!

**Comment by hflynn** [comment]
As discussed today, I'll take over this branch and open a new PR today with the blurb added, thanks @lunson

**Pull request closed without merging**
