### PR TITLE
Add icons

### PR DESCRIPTION
**Pull request by lunson**
My update for Monday meeting (I am away that day due to dentist and doc appts): working on icons and other graphics. These are just the OMERO feature icons. 

More to come.

### CODE REVIEW

**Comment by sbesson** [comment]
:+1: Note this branch currently conflicts on `products/ome-files/index.html` so you might want to either rebase it or merge the latest changed merged in `master`.

Following https://github.com/openmicroscopy/www.openmicroscopy.org/pull/17, I have the beginning of a branch to re-enable `htmlproofer` including the check of internal links. Most of the failures (~220 so far) are due to the absence of `alt` attributes for images. I will wait until this gets reviewed and merged before opening it to prevent unnecessary conflict.

**Comment by hflynn** [comment]
Since Liza isn't here today, I'll fetch this branch this morning and fix up the conflicts so we can get it built to discuss this pm.

**Comment by lunson** [comment]
@hflynn Thank you, Helen! If all else fails, go with @sbesson's content changes as mine are just cosmetic.

**Comment by hflynn** [comment]
Opened a new PR with the master branch merged. I'm assuming you won't be working on this again til tomorrow now @lunson so we'll look at this branch and merge the work so far so you can continue on a fresh branch from master tomorrow.

**Pull request closed without merging**
