### PR TITLE
Add 2014 users meeting & pdf icons

### PR DESCRIPTION
**Pull request by hflynn**
See https://trello.com/c/2zHi3RMN/116-add-other-user-meetings

Content taken from https://www-legacy.openmicroscopy.org/site/community/minutes/meetings/9th-annual-users-meeting-june-2014

### CODE REVIEW

**Comment by hflynn** [comment]
2nd commit implements RFE requested by @manics on #161 (https://trello.com/c/XpuH9x9V/126-add-pdf-icon-to-pdf-links-events-pages)

**Comment by hflynn** [comment]
Staged at https://snoopycrimecop.github.io/www.openmicroscopy.org/events/9th-annual-users-meeting-june-2014.html etc

**Comment by hflynn** [comment]
I've followed the style of https://snoopycrimecop.github.io/www.openmicroscopy.org/training/ and left the icon outside the anchor link

**Comment by jburel** [comment]
the presentations under workshop should open in a new tab similar to the talks.
i.e. add ```target="_blank"```
The icons are displayed correctly

**Comment by hflynn** [comment]
https://snoopycrimecop.github.io/www.openmicroscopy.org/events/ updated now, think I've caught them all @jburel

**Comment by hflynn** [comment]
Happy for this to be merged now @jburel ?

**Comment by jburel** [comment]
The display for poster session
for https://snoopycrimecop.github.io/www.openmicroscopy.org/events/10th-annual-users-meeting-june-2015.html
and https://snoopycrimecop.github.io/www.openmicroscopy.org/events/11th-annual-users-meeting-2016.html
could be unified
They both point to similar folder. I prefer the 2016 version
same thing https://snoopycrimecop.github.io/www.openmicroscopy.org/events/9th-annual-users-meeting-june-2014.html

Are you thinking to add later on a movie icon for the movie version?

**Comment by hflynn** [comment]
@jburel change pushed. Not sure on the movie icon front - Simon requested a pdf icon specifically to warn when the browser might be slow loading because it's a pdf.

@lunson is there one of the fa-fa icons for movies?

**Comment by jburel** [comment]
for movie this is not a big deal. I was more curious

**Comment by hflynn** [comment]
Actually, looked it up myself - what do you think of this one http://fontawesome.io/icon/file-video-o/ ?

**Comment by hflynn** [comment]
I'm loathe to start cluttering the links up a lot but it would maybe make the movie links on https://snoopycrimecop.github.io/www.openmicroscopy.org/events/11th-annual-users-meeting-2016.html more obvious, want me to try it?

**Comment by jburel** [comment]
you could try on one link and see how it looks

**Comment by lunson** [comment]
@hflynn http://fontawesome.io/icon/file-video-o/ should work just fine!

**Comment by hflynn** [comment]
https://snoopycrimecop.github.io/www.openmicroscopy.org/events/11th-annual-users-meeting-2016.html updated @jburel - took a bit of tweaking for the spacing but I think it looks okay now

**Comment by jburel** [comment]
I think it looks good with the icon
thanks

**Comment by hflynn** [comment]
Good to merge then?

**Comment by jburel** [comment]
Sorry good to merge
Thanks @hflynn

**Pull request merged**
