### PR TITLE
add Google Analytics tracking ID

### PR DESCRIPTION
**Pull request by lunson**
Adds OME's Google Analytics tracking ID

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by joshmoore** [comment]
Looks like we need a new suffix (now 4 for testing on infra-testpr). @sbesson : could this be made configurable so that we can test on staging, etc?

@lunson : a different block of code is suggested:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49953125-4', 'auto');
  ga('send', 'pageview');

</script>
```

Do you know anything about the differences to what you have?

**Comment by lunson** [comment]
@joshmoore No, I basically copied GS's script and changed the tracking ID and website url.

**Comment by joshmoore** [comment]
Thanks, @lunson. This will certainly help for all infra-testpr testing. I'll work with @sbesson to define the production identifier.

**Comment by joshmoore** [comment]
:+1:

**Comment by sbesson** [comment]
Depending on where we want to define this, I could see it handled via the `_prod.yml` file introduced in https://github.com/openmicroscopy/www.openmicroscopy.org/pull/92. I would propose to merge this and try to move the token into the YML there if there is no objection.

**Pull request merged**
