### PR TITLE
Add version & release link to ome files downloads

### PR DESCRIPTION
**Pull request by hflynn**
To match the others

### CODE REVIEW

**Comment by hflynn** [comment]
https://snoopycrimecop.github.io/www.openmicroscopy.org/ome-files/downloads/ updated

**Comment by rleigh-codelibre** [comment]
Broken Links: top row, all CentOS 6, MacOS X and FreeBSD links.

**Comment by hflynn** [comment]
@rleigh-codelibre is fixing the links on a separate PR, this should be good to merge

**Comment by joshmoore** [comment]
Thanks all.

**Pull request merged**
