### PR TITLE
Add warning banner and updated announcements re: 5.4.2 web issue

### PR DESCRIPTION
**Pull request by hflynn**
Replaces #185 

Issue announcement text taken from https://docs.google.com/document/d/18CxNkE80NWIIB2Ho2BjlFkfs-e-Q2JPO1DO9NvFJ1EY/edit

### CODE REVIEW

**Comment by hflynn** [comment]
Staged at https://snoopycrimecop.github.io/www.openmicroscopy.org/omero/downloads/, https://snoopycrimecop.github.io/www.openmicroscopy.org/2018/01/26/omero-5-4-2-issue.html and https://snoopycrimecop.github.io/www.openmicroscopy.org/2018/01/23/omero-5-4-2.html

**Comment by joshmoore** [comment]
https://snoopycrimecop.github.io/www.openmicroscopy.org/omero/downloads -- that's quite effective. I could see removing the "please see the announcement" banner to make it clearer which is important (currently the same color)

**Comment by hflynn** [comment]
Do you want me to remove it or replace it with the new banner there rather than further down the page?

**Comment by joshmoore** [comment]
Hmmm..... not sure. To some extent, it depends on how we reference the changes in 5.4.2. i.e. if 5.4.3 just says, "this is a re-release of 5.4.2 fixing the file leak" then someone will need to make it to the 5.4.2 announcement, etc.

**Comment by hflynn** [comment]
Okay, I'll comment it out for now

**Comment by hflynn** [comment]
https://snoopycrimecop.github.io/www.openmicroscopy.org/omero/downloads/ updated, good to merge and deploy now @joshmoore ?

**Comment by joshmoore** [comment]
Hmmm.... sorry for being problematic, but can we have it like "read the docs" i.e. de-emphasized, but still available?

**Comment by hflynn** [comment]
https://snoopycrimecop.github.io/www.openmicroscopy.org/omero/downloads/ better?

**Comment by joshmoore** [comment]
Yes, thank you. "The defense rests, your honor"

**Pull request merged**
