### PR TITLE
Fix more html proofing issues & add grant links

### PR DESCRIPTION
**Pull request by hflynn**
Fixing missing alt image tags and missing links

### CODE REVIEW

**Comment by hflynn** [comment]
Link fixes to follow

**Comment by hflynn** [comment]
Down to only 15 failures now and @lunson is still working on the OMERO product section images so I'll leave those missing alt tags for now and fix any left over once she's done.

Main things remaining now are the full list of "Examples of OME’s resources are used in the following" for which I'm wondering if we could do a pop-up like the team bios (what do you think @lunson?) and the imaging domain link which I'll likely comment out for now as we don't have the content done.

**Comment by hflynn** [comment]
Chatted to Liza briefly, I'll just add any further links needed to the existing list and delete the full list link. I just need to check where the list came from tomorrow & how many more companies there are to list.

**Comment by sbesson** [comment]
Changes deployed to https://snoopycrimecop.github.io/www.openmicroscopy.org and make sense. Checked funding links manually as the `htmlproofer` is only running internally in this phase. Ready to merge.

**Pull request merged**
