### PR TITLE
Announcement fpbioimage 0.3.0

### PR DESCRIPTION
**Pull request by jburel**
Announcement

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by mtbc** [comment]
Staged at https://snoopycrimecop.github.io/www.openmicroscopy.org/2018/10/09/fpbioimage-0-3-0.html.

**Comment by mtbc** [comment]
Slightly strange that OMERO.FPBioimage 0.3.0 brings us Version 4 of FPBioimage but I assume that makes sense to somebody.

**Comment by jburel** [comment]
It is the versioning using by FPBioimage, not under our control.
It is not a version our plugin that we can have as a major version

**Comment by jburel** [comment]
Merging 
This will be tagged with 5.4.9

**Pull request merged**
