### PR TITLE
Bio-Formats 5.8.0 release

### PR DESCRIPTION
**Pull request by hflynn**
See https://trello.com/c/OeKLlak7/28-open-pr-against-wwwopenmicroscopyorg and https://github.com/openmicroscopy/bioformats/pull/3076

### CODE REVIEW

**Comment by hflynn** [comment]
Staged at https://snoopycrimecop.github.io/www.openmicroscopy.org/bio-formats/ https://snoopycrimecop.github.io/www.openmicroscopy.org/bio-formats/downloads/ and https://snoopycrimecop.github.io/www.openmicroscopy.org/2018/02/20/bio-formats-5-8-0.html

**Comment by rleigh-codelibre** [comment]
Looks fine to me.  Though I do wonder for future releases if we need to duplicate all the changes here; could we not simply link to the bioformats documentation which already contains them?

**Comment by hflynn** [comment]
I've wondered about this too, but it is easier to copy & paste the whole lot and use the text for the emails too than the produce an edited version.

**Comment by hflynn** [comment]
https://snoopycrimecop.github.io/www.openmicroscopy.org/2018/02/21/bio-formats-5-8-0.html updated

**Comment by hflynn** [comment]
Downloads page reviewed as fine on release testing board and this text matches the version history which has been merged so merging this for release this afternoon.

**Pull request merged**
