### PR TITLE
Bio-Formats 5.7.3 release

### PR DESCRIPTION
**Pull request by hflynn**
Based on https://github.com/openmicroscopy/bioformats/pull/3035

### CODE REVIEW

**Comment by hflynn** [comment]
Staged at https://snoopycrimecop.github.io/www.openmicroscopy.org/bio-formats/downloads/ and https://snoopycrimecop.github.io/www.openmicroscopy.org/2018/01/11/bio-formats-5-7-3.html

Note that artifact download links won't work until the release is built

**Comment by hflynn** [comment]
Last commit to match https://github.com/openmicroscopy/bioformats/pull/3035/commits/2f19e00ceb63592dacaf741e6ab3a9ef1920f598

**Comment by hflynn** [comment]
https://snoopycrimecop.github.io/www.openmicroscopy.org/2018/01/11/bio-formats-5-7-3.html updated

**Comment by dgault** [comment]
Updates look good. Everything displays correctly and the links are all working. Looks good to merge.

**Pull request merged**
