### PR TITLE
Next workshop

### PR DESCRIPTION
**Pull request by jburel**
Update front page to promote next workshop

### CODE REVIEW

**Comment by jburel** [comment]
We can certainly combine them.
Pushing my commit to @will-moore's PR now

**Comment by jburel** [comment]
Closing. Pushed commit to https://github.com/openmicroscopy/www.openmicroscopy.org/pull/243

**Comment by will-moore** [comment]
Do we want to remove the Dundee image ```header id="bg-image-users-meeting"``` too and revert so microscopy image as before?
Then the change would be more noticeable too.

**Comment by jburel** [comment]
I don't think it is "Dundee" specific. Plane and submarine mean "travel/on the road" so I thought it was still legitimate to keep it

**Pull request closed without merging**
