### PR TITLE
10th User meeting content

### PR DESCRIPTION
**Pull request by hflynn**
Adds the content from https://www-legacy.openmicroscopy.org/site/community/minutes/meetings/10th-annual-users-meeting-june-2015 to the new website

see https://trello.com/c/2zHi3RMN/116-add-other-user-meetings

### CODE REVIEW

**Comment by hflynn** [comment]
Staged at https://snoopycrimecop.github.io/www.openmicroscopy.org/events/ and 
https://snoopycrimecop.github.io/www.openmicroscopy.org/events/10th-annual-users-meeting-june-2015.html

**Comment by hflynn** [comment]
N.B. the 'june' in the URL/filename is to match the old URL for redirection, I'm aware it doesn't match the earlier entries

**Comment by manics** [comment]
Looks fine to me.

Future RFE: add a pdf icon next to the PDF links since they're quite large and can slow down the browser

**Comment by hflynn** [comment]
Thanks @manics I've added a card to the website board for the RFE

**Pull request merged**
