### PR TITLE
tone down the gray

### PR DESCRIPTION
**Pull request by lunson**
See: https://trello.com/c/TrhPxqsH/136-cli-quoting-too-glaring

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [WWW-merge#451](https://ci.openmicroscopy.org/job/WWW-merge/451/). See the [console output](https://ci.openmicroscopy.org/job/WWW-merge/451/consoleText) for more details.
Possible conflicts:
  - PR #149 lunson 'Add media layouts'
    - css/openmicroscopy.css

--conflicts

**Comment by hflynn** [comment]
I'll exclude the media layouts for now

**Comment by hflynn** [comment]
https://snoopycrimecop.github.io/www.openmicroscopy.org/2018/01/23/omero-5-4-2.html looks good to me, happy @joshmoore ?

**Comment by hflynn** [comment]
👍

**Pull request merged**
