### PR TITLE
add flimfit to Analyze features

### PR DESCRIPTION
**Pull request by lunson**
Adds FLIMfit to list of OMERO features under Analyze

### CODE REVIEW

**Comment by hflynn** [comment]
Staged at https://snoopycrimecop.github.io/www.openmicroscopy.org/omero/analyze/

**Comment by hflynn** [comment]
Looks good to me, you happy @jburel ?

**Comment by jburel** [comment]
Thanks looks great

**Comment by hflynn** [comment]
I see Sean still has their website linking to our licensing page so I've submitted an issue for him to update it. Can this go live today @jburel or are we waiting on them releasing a new version?

**Comment by hflynn** [comment]
Confirmed as good to go

**Pull request merged**
