### PR TITLE
figure 3.2.0 announcement

### PR DESCRIPTION
**Pull request by will-moore**
Ported from https://github.com/ome/omero-figure/pull/261

### CODE REVIEW

**Comment by hflynn** [comment]
Rebuilding the snoopy staging site now

**Comment by hflynn** [comment]
https://snoopycrimecop.github.io/www.openmicroscopy.org/2018/01/30/figure-3-2-0.html looks good

**Comment by jburel** [comment]
Will it possible to open help and video in a new tab?

**Comment by hflynn** [comment]
Ah yeah, good idea @jburel - that is the policy we use elsewhere on the site for external links.

**Comment by will-moore** [comment]
None of the other announcements open another tab for links (just checked the last few).
Also I think it's generally a bad idea to open links in a new tab for a webpage (I guess it's OK for apps like gdoc or trello) but e.g. github doesn't do it.
e.g. https://www.smashingmagazine.com/2008/07/should-links-open-in-new-windows/

**Comment by hflynn** [comment]
I give @jburel final say, I copied Liza's implementation elsewhere on the site but default to leaving users to open their own tab in general so obviously forgot for the announcements!

**Comment by jburel** [comment]
in our we go to different websites
that's what we have done for example here
https://snoopycrimecop.github.io/www.openmicroscopy.org/omero/publish/
click on the video and it opens a new tab

**Comment by will-moore** [comment]
Fixed links to open in new tab.

**Comment by hflynn** [comment]
👍

**Pull request merged**
