### PR TITLE
Add Docker Hub link to Explore

### PR DESCRIPTION
**Pull request by hflynn**
See https://trello.com/c/ULleHgKM/2-social-links

Happy to add other additions here or on the on-the-web page is there's something else we want to promote - card was originally for Ohloh/Open Hub which we've since ditched.

### CODE REVIEW

**Comment by hflynn** [comment]
Staged at https://snoopycrimecop.github.io/www.openmicroscopy.org/explore/

**Comment by hflynn** [comment]
https://snoopycrimecop.github.io/www.openmicroscopy.org/explore/ updated with a wording tweak for Josh.

**Comment by hflynn** [comment]
Happy for me to merge this now @joshmoore ?

**Comment by joshmoore** [comment]
Yup. Thank you.

**Pull request merged**
