### PR TITLE
Fix docs links

### PR DESCRIPTION
**Pull request by lunson**
See https://trello.com/c/hkvSttvR/127-docs-page-has-unnecessary-read-on-the-web-links

### CODE REVIEW

**Comment by lunson** [comment]
Closing PR. I realized I targeted the wrong tag.

**Comment by lunson** [comment]
Fixed HTML structure.

**Comment by hflynn** [comment]
https://snoopycrimecop.github.io/www.openmicroscopy.org/docs/ updated - the boxes aren't a consistent size which looks a bit odd - especially for OME Files where the box ends up being the biggest despite it having the smallest amount of text

**Comment by hflynn** [comment]
Of course now I realise the boxes are the same on the live page, I just never noticed before!

**Comment by hflynn** [comment]
Looks a lot better now thanks - they still aren't exactly the same but it's a lot less glaring now.

Happy with this @manics ?

**Comment by manics** [comment]
That's a lot better 👍

**Pull request merged**
