### PR TITLE
Training freising

### PR DESCRIPTION
**Pull request by jburel**
Add new entry for upcoming workshop

cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
The built page looks good. https://snoopycrimecop.github.io/www.openmicroscopy.org/

Do we want to wait with merge until we get ``final final`` confirm from Freising on the dates ?

**Comment by jburel** [comment]
We can always adjust if there is a change.

**Comment by pwalczysko** [comment]
Merge then ?

**Comment by jburel** [comment]
Merging and redeploying the website

**Pull request merged**
