### PR TITLE
Add bg images and logos

### PR DESCRIPTION
**Pull request by lunson**
includes removal of hyphen from OME Files logo

### CODE REVIEW

**Comment by hflynn** [comment]
This seems to include all the latest changes on one branch, is there a reason it's closed?

**Comment by lunson** [comment]
I'm adding some features icons on it. I'll push once I finish a set.

**Comment by hflynn** [comment]
Ah okay @lunson

**Comment by hflynn** [comment]
Might be easier to start the features on the fresh branch though and open a 2nd PR for them so we can get this in?

**Pull request merged**
