### PR TITLE
change links to OME help to use HTTPS

### PR DESCRIPTION
**Pull request by mtbc**
See https://trello.com/c/mTAsiIpK/4014-help-website-has-bad-certificate.

### CODE REVIEW

**Comment by kennethgillen** [comment]
@sbesson @joshmoore  - I see published posts using the `http` link still: is it worth tacking that onto this PR, or is that PR scope creep?

```
2018-06-28 10:21 LS27172:www.openmicroscopy.org kenny$ grep -R -Po 'https?://(\w|\d|\.|\/|-|\?|=|&)*\b' * | grep "http://help"
_posts/2014-02-25-omero-bio-formats-5-0-0.md:http://help.openmicroscopy.org/imagej.html
_posts/2015-12-17-omero-5-2-1.md:http://help.openmicroscopy.org/imagej.html
_posts/2014-08-06-omero-bio-formats-5-0-3.md:http://help.openmicroscopy.org/search.html
_posts/2018-01-30-figure-3-2-0.md:http://help.openmicroscopy.org/figure.html
```

**Comment by mtbc** [comment]
Good point: I should have mentioned avoiding those being leery of retrospectively editing timestamped entries. Happy to change them if desired though.

**Comment by jburel** [comment]
last time we had a round of "http->htpps" fixes, we also updated the posts if I remember correctly

**Comment by jburel** [comment]
otherwise it looks good

**Comment by mtbc** [comment]
See https://trello.com/c/z0MqRssM/459-more-https-links. My PRs this week are *not* comprehensive: I confined myself to the easier obvious pickings that were clearly not controversial.

**Pull request merged**
