### PR TITLE
add statement about not-insecure OMERO versions

### PR DESCRIPTION
**Pull request by mtbc**
A typical interest in https://snoopycrimecop.github.io/www.openmicroscopy.org/security/ is probably the simple,

> Is my OMERO known to be vulnerable?

This PR offers a fast answer.

### CODE REVIEW

**Comment by hflynn** [comment]
wfm - https://snoopycrimecop.github.io/www.openmicroscopy.org/security/ looks fine

**Comment by joshmoore** [comment]
Is it noted somewhere (secvuln release process?) when this version should be bumped?

**Comment by mtbc** [comment]
No, I don't believe that the documentation step of the process is itself documented.

**Comment by mtbc** [comment]
In the meantime, we could put a reminder as a HTML comment on the advisory list page.

**Comment by hflynn** [comment]
I'll put a reminder on the appropriate template card

**Comment by mtbc** [comment]
Ahh, good idea @hflynn, I had forgotten those.

**Comment by hflynn** [comment]
https://trello.com/c/IDC20Rts/84-prepare-security-advisories

**Pull request merged**
