### PR TITLE
Add Facebook preview image

### PR DESCRIPTION
**Pull request by lunson**
See https://trello.com/c/grpWZ8U0/129-when-posting-wwwopenmicroscopyorg-on-facebook-the-jcb-data-viewer-logo-is-the-one-that-gets-used

### CODE REVIEW

**Comment by hflynn** [comment]
Tested using the staging URL on my personal facebook account - looks good to me

fb_preview

**Comment by hflynn** [comment]
Tested linking to a subpage too and the preview is the same

**Comment by hflynn** [comment]
Good to merge from me, will leave others to comment before doing so though.

**Comment by joshmoore** [comment]
Nice! Thanks all.

**Pull request merged**
