### PR TITLE
Remove URLs to registration URL for 2018 Users meeting

### PR DESCRIPTION
**Pull request by sbesson**
The only leftover place is the post from February 23th which we could edit or leave in place.

### CODE REVIEW

**Comment by kennethgillen** [comment]
Would you leave "Join us May 30th to June 1st in Dundee!" if there's no link to registration?
screen shot 2018-05-07 at 12 59 35

**Comment by kennethgillen** [comment]
I'd think it make sense to keep the date clearly visible, so LGTM. Though is Internal/OME slack:  https://openmicroscopy.slack.com/archives/C0K5EED3R/p1525692075000224 destined for here?

**Comment by sbesson** [comment]
Deployed live.

**Comment by kennethgillen** [comment]
👍

**Comment by jrswedlow** [comment]
Banner should point to the meeting page: https://www.openmicroscopy.org/events/13th-annual-users-meeting-2018.html

**Comment by sbesson** [comment]
The removal of the `See the schedule` link was an oversight. It should be restored in https://github.com/openmicroscopy/www.openmicroscopy.org/pull/223 alongside the addition of the programme

**Pull request merged**
