### PR TITLE
Comment out imaging domains & remove unneeded link

### PR DESCRIPTION
**Pull request by hflynn**
More tidying ready for the POTN preview - commented out the imaging domains section on the home page (not a priority right now to generate further content for this) and removed the unneeded link from the examples of OME resource use in external projects - when I checked back this list, we already included all the items on the current live website page so no extension was needed.

### CODE REVIEW

**Comment by hflynn** [comment]
Remaining html proofer failures are all missing alt image tags in the OMERO product sections, I'll clean up any left over once @lunson is finished work on those pages

**Comment by hflynn** [comment]
Staged at https://snoopycrimecop.github.io/www.openmicroscopy.org/index.html and https://snoopycrimecop.github.io/www.openmicroscopy.org/about/

**Comment by sbesson** [comment]
With #37 included, you should now be able to merge `origin/master` into this branch and remove `|| echo "Failed"` from https://github.com/openmicroscopy/www.openmicroscopy.org/blob/master/.travis.yml#L11

**Comment by hflynn** [comment]
Proofer all green

**Pull request merged**
