### PR TITLE
logos for code

### PR DESCRIPTION
**Pull request by jburel**
Add file so broken links can be fixed in code
Item come from openmicroscopy-legacy
* ``.ico`` from ``OME-WEBSITE`` folder

### CODE REVIEW

**Comment by hflynn** [comment]
Do we really need to keep the old logo, could we not just delete the link?

**Comment by jburel** [comment]
The section explains how to replace the default logo in the login screen
We could try to rephrase it

**Comment by jburel** [comment]
Actually I could change it and point it to the logo currently in the code repo
Removing from website

**Comment by jburel** [comment]
Closing this PR
Since I have found favicon.ico in resources (I missed it before)

**Pull request closed without merging**
