### PR TITLE
optimize OMERO pages navigation

### PR DESCRIPTION
**Pull request by lunson**
Not ready for merge. Just need to draw attention to https://trello.com/c/IRGd8elG/141-optimize-omero-pages-navigation in order to prepare for the OMERO.figure and iviewer landing pages. Thanks!

### CODE REVIEW

**Comment by hflynn** [comment]
@waxenegger can you work your setting the active item magic again here that you did on #149 please? I'm afraid we're not having any joy trying to copy what you did!

**Comment by hflynn** [comment]
Staged at https://snoopycrimecop.github.io/www.openmicroscopy.org/omero/ btw - looks good once we get it working properly :)

**Comment by waxenegger** [comment]
@hflynn how are this PR and https://github.com/openmicroscopy/www.openmicroscopy.org/pull/149 related and are they going in both (eventually)? 

Reason I'm asking is that the other is at the moment not merged/excluded, also that they are going to conflict. For the purpose of this PR some adjustments like https://github.com/waxenegger/www.openmicroscopy.org/commit/7317fabcc8e0336db0f5c83c4ee50c2c9179ebdc should probably do the job.

**Comment by hflynn** [comment]
@waxenegger 149 is already conflicting but will go in eventually. Thanks for the commit!

**Comment by hflynn** [comment]
Replaced by #193

**Pull request closed without merging**
