### PR TITLE
Add Feature icons

### PR DESCRIPTION
**Pull request by hflynn**
Replaces #18 

Adding Feature icons for OMERO

### CODE REVIEW

**Comment by hflynn** [comment]
Staged at https://snoopycrimecop.github.io/www.openmicroscopy.org/products/omero/

**Comment by hflynn** [comment]
Also icons added on https://snoopycrimecop.github.io/www.openmicroscopy.org/support/

**Comment by hflynn** [comment]
@lunson a bit concerned about the contrast between the white text and the brighter spots of the background image for the headers on https://snoopycrimecop.github.io/www.openmicroscopy.org/products/omero/ and https://snoopycrimecop.github.io/www.openmicroscopy.org/products/bio-formats/ - maybe we could have a darker shaded box behind the text or something?

**Comment by lunson** [comment]
@hflynn Yup, it's still on my To Do to play with the background and text shadows.

**Comment by hflynn** [comment]
Icons also added to https://snoopycrimecop.github.io/www.openmicroscopy.org/about/commercial-partners/

**Comment by hflynn** [comment]
Looking good in general but I'm wondering if we should avoid using the GitHub logo for partner projects smuggler and wnd-charm? I know the projects are hosted there but then so is all of our stuff

**Comment by lunson** [comment]
@hflynn Understood, but what imagery would best represent both? When I think smuggler, I picture a burglar; when I see wnd-charm, I picture wind charms. I don't know enough about either project to create a better representation. Help?

**Comment by hflynn** [comment]
So smuggler is an import tool which uses a queue so maybe just the import arrow design or some variation of it inside the circle and wnd-charm is machine learning pattern recognition tool so maybe make the centre circle into target sights?

**Comment by hflynn** [comment]
@lunson if it's ok with you, I'll delete those two icons and then merge this, then you can carry on a frsh branch tomorrow

**Comment by hflynn** [comment]
Checking https://github.com/logos those adapted icons fall foul of their logo usage rules anyway.

**Pull request merged**
